[package]
name = "xds-api"
version = "0.2.0"
edition = "2021"
authors = ["Junction Labs"]
license = "Apache-2.0"
repository = "https://github.com/junction-labs/xds-api"
homepage = "https://github.com/junction-labs/xds-api"
readme = "README.md"
description = """
Protocol buffer types for working with Envoy's xDS APIs.
"""
keywords = ["grpc", "xds", "envoy"]
# we use std::sync::LazyLock
rust-version = "1.81"

[workspace]
members = [".", "xtask"]

[workspace.dependencies]
pbjson = "0.7"
pbjson-build = "0.7"
prost = "0.13"
prost-build = "0.13"
prost-types = "0.13"
serde = "1.0"
tonic = { version = "0.12", default-features = false }
tonic-build = { version = "0.12", default-features = false }

[lib]
doctest = false


[dependencies]
enum-map = "2.7"
prost.workspace = true
tonic = { workspace = true, default-features = false, features = [
    "prost",
    "codegen",
] }
pbjson = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[features]
pbjson = ["dep:pbjson", "dep:serde"]
descriptor = []
